import test from 'node:test'
import assert from 'node:assert/strict'
import { mkdtemp, mkdir, writeFile } from 'node:fs/promises'
import os from 'node:os'
import path from 'node:path'
import { ARENA_PROVIDER_IDS, PRIMARY_ARENA_PROVIDER_IDS, arenaDashboard, assertBenchmarkMutable, assertSameInputFairness, calculateRoundWinner, computeBenchmarkLockHash, createArenaBatch, createArenaRound, createBlindMapping, createQuestionBankEntry, migrateArenaState, publicArenaRound, recordArenaJudgment, revealArenaRound, rotateExecutionOrder, scoreVerdict } from '../src/arena/index.mjs'
import { buildArenaBundle, buildPrivateMappingBundle } from '../src/arena/export.mjs'

function fixture() {
  const state = { schemaVersion: 4, photos: [{ id: 'photo-1', filename: 'dog.jpg', storedFilename: 'dog.jpg', inferenceFilename: 'dog.png', inferenceImageSha256: 'a'.repeat(64), imagePipeline: { ready: true } }], datasets: [{ id: 'dataset-1', photoIds: ['photo-1'] }], inferences: [], migrations: {} }
  migrateArenaState(state, '2026-08-15T10:00:00.000Z')
  return state
}
let roundCounter = 0
function roundIn(state, providerIds = ARENA_PROVIDER_IDS.slice(0, 2), random = () => .99) {
  roundCounter += 1
  const round = createArenaRound({ photoId: 'photo-1', datasetId: 'dataset-1', question: 'What is visible?', category: 'object_recognition', providerIds, outputBudget: 64 }, state, { now: '2026-08-15T10:00:00.000Z', idFactory: () => `r${String(roundCounter).padStart(7, '0')}`, random })
  round.runId = 'run-1'; state.arenaRounds.push(round); return round
}
function attachAnswers(state, round) {
  for (const [label, providerId] of Object.entries(round.blindMapping)) {
    const inference = { id: `answer-${label}`, arenaRoundId: round.id, runId: 'run-1', blindLabel: label, photoId: round.photoId, inferenceImage: round.inferenceImage, prompt: round.question, outputBudget: round.outputBudget, providerId, rawOutput: `output ${label}`, validationResult: 'VALID', latencyMs: label === 'A' ? 100 : 200, runtime: 'local', model: `secret-${providerId}`, runtimeStats: { cold_start_ms: 25 } }
    state.inferences.push(inference); round.answerIds[label] = inference.id
  }
  round.status = 'AWAITING_JUDGMENT'
}

test('Arena migration is additive and creates an empty starter set', () => { const state = fixture(); assert.equal(state.schemaVersion, 6); assert.equal(state.arenaBenchmarkSets[0].status, 'EMPTY'); assert.deepEqual(state.arenaBenchmarkSets[0].questionIds, []) })
test('blind mapping is injective and randomized without changing participants', () => { const a = createBlindMapping(['one','two','three'], () => 0); const b = createBlindMapping(['one','two','three'], () => .99); assert.deepEqual(new Set(Object.values(a)), new Set(Object.values(b))); assert.notDeepEqual(a, b) })
test('fair primary roster is exact and execution order rotates independently of blind labels', () => { assert.deepEqual(PRIMARY_ARENA_PROVIDER_IDS, ['visionpsy-patched-base','lfm2.5-vl-450m','qvac-smolvlm2']); assert.deepEqual(rotateExecutionOrder(PRIMARY_ARENA_PROVIDER_IDS, 1), ['lfm2.5-vl-450m','qvac-smolvlm2','visionpsy-patched-base']) })
test('public round does not leak identities, ground truth, runtimes, mapping, or latency before reveal', () => { const state = fixture(); const round = roundIn(state); round.expectedAnswer = 'private expected answer'; round.expectedAnswerSource = 'USER_DEFINED_GROUND_TRUTH'; attachAnswers(state, round); const text = JSON.stringify(publicArenaRound(round, state)); for (const secret of [...round.providerIds, 'private expected answer', 'USER_DEFINED_GROUND_TRUTH', 'secret-', 'blindMapping', 'latencyMs', 'runtimeStats']) assert.equal(text.includes(secret), false) })
test('same-input fairness requires exact image, prompt, budget, and provider coverage', () => { const state = fixture(); const round = roundIn(state); attachAnswers(state, round); assert.equal(assertSameInputFairness(round, state.inferences), true); state.inferences[0].prompt = 'different'; assert.throws(() => assertSameInputFairness(round, state.inferences), /fairness/) })
test('verdict scoring follows 2, 1, 0, -1 and excludes unclear', () => { assert.equal(scoreVerdict('CORRECT'), 2); assert.equal(scoreVerdict('PARTIALLY_CORRECT'), 1); assert.equal(scoreVerdict('WRONG'), 0); assert.equal(scoreVerdict('HALLUCINATED'), -1); assert.equal(scoreVerdict('UNCLEAR_IMAGE'), null) })
test('multiple judgments preserve provenance and disagreement', () => { const state = fixture(); const round = roundIn(state); attachAnswers(state, round); recordArenaJudgment(state, { roundId: round.id, blindLabel: 'A', verdict: 'CORRECT' }, { idFactory: () => 'one' }); recordArenaJudgment(state, { roundId: round.id, blindLabel: 'A', verdict: 'WRONG', judgeProviderId: 'LOCAL_AI_JUDGE' }, { idFactory: () => 'two' }); assert.equal(state.arenaJudgments.length, 2); assert.deepEqual(state.arenaJudgments.map(item => item.provenance), ['USER_JUDGE','LOCAL_AI_JUDGE']) })
test('clients cannot forge deterministic gold judgments', () => { const state = fixture(); const round = roundIn(state); attachAnswers(state, round); assert.throws(() => recordArenaJudgment(state, { roundId: round.id, blindLabel: 'A', verdict: 'CORRECT', judgeProviderId: 'GOLD_ANSWER_SCORER' }), /only be created by the server/) })
test('normal reveal requires every answer judged and records a valid blind review', () => { const state = fixture(); const round = roundIn(state); attachAnswers(state, round); assert.throws(() => revealArenaRound(round, state.arenaJudgments), /Judge every/); for (const label of Object.keys(round.blindMapping)) recordArenaJudgment(state, { roundId: round.id, blindLabel: label, verdict: label === 'A' ? 'CORRECT' : 'WRONG' }); revealArenaRound(round, state.arenaJudgments, {}, { now: '2026-08-15T11:00:00.000Z' }); assert.equal(round.blindStatus, 'BLIND_VALID'); assert.equal(round.reviewMode, 'BLIND_REVIEW'); assert.ok(round.winnerProviderId) })
test('early reveal is permanently marked NON_BLIND_REVIEW', () => { const state = fixture(); const round = roundIn(state); attachAnswers(state, round); revealArenaRound(round, [], { early: true }); assert.equal(round.blindStatus, 'NON_BLIND'); assert.equal(round.reviewMode, 'NON_BLIND_REVIEW'); assert.equal(round.judgedBeforeReveal, false) })
test('winner calculation handles ties and no valid judgment', () => { const state = fixture(); const round = roundIn(state); attachAnswers(state, round); assert.equal(calculateRoundWinner(round, [], state.arenaScoring).winner, 'NO_VALID_JUDGMENT'); for (const label of Object.keys(round.blindMapping)) recordArenaJudgment(state, { roundId: round.id, blindLabel: label, verdict: 'CORRECT' }); assert.equal(calculateRoundWinner(round, state.arenaJudgments, state.arenaScoring).winner, 'TIE') })
test('dashboard ranks only blind-valid primary rounds and excludes exploratory rounds', () => { const state = fixture(); const exploratory = roundIn(state); attachAnswers(state, exploratory); revealArenaRound(exploratory, [], { early: true }); const round = roundIn(state, PRIMARY_ARENA_PROVIDER_IDS); round.arenaMode = 'FAIR_RESOURCE_MATCHED_PRIMARY'; attachAnswers(state, round); for (const label of Object.keys(round.blindMapping)) recordArenaJudgment(state, { roundId: round.id, blindLabel: label, verdict: label === 'A' ? 'CORRECT' : 'HALLUCINATED' }); revealArenaRound(round, state.arenaJudgments); const dashboard = arenaDashboard(state); assert.equal(dashboard.metrics.length, 3); assert.equal(dashboard.sharedReviewedRounds, 1); assert.equal(dashboard.exploratoryRoundCount, 1); assert.equal(dashboard.rankingEligible, false); assert.ok(Object.keys(dashboard.headToHead).length) })
test('locked benchmark atomically creates reciprocal round and run records', () => { const state = fixture(); const set = state.arenaBenchmarkSets[0]; const categories = ['object_recognition','color_detail','spatial_relation','physical_context','visual_text','number_value','ui_understanding','document_understanding','chart_table','other']; for (let index = 0; index < 30; index++) { const photoId = `photo-${index + 2}`; state.photos.push({ id: photoId, filename: `${photoId}.jpg`, storedFilename: `${photoId}.jpg`, inferenceFilename: `${photoId}.png`, inferenceImageSha256: 'b'.repeat(64), imagePipeline: { ready: true } }); state.datasets[0].photoIds.push(photoId); const question = createQuestionBankEntry({ text: `Read the sign ${index}`, category: categories[index % categories.length], photoId, datasetId: 'dataset-1', expectedAnswer: String(index), answerType: 'integer' }, state, { idFactory: () => `q${index}` }); set.questionIds.push(question.id) } const batch = createArenaBatch({ benchmarkSetId: set.id, providerIds: ARENA_PROVIDER_IDS.slice(0,2), locked: true }, state, { idFactory: () => randomToken(), random: () => .5 }); const round = state.arenaRounds.find(item => item.id === batch.roundIds[0]); const run = state.runs.find(item => item.id === round.runId); assert.equal(batch.status, 'DRAFT'); assert.equal(batch.roundIds.length, 30); assert.equal(batch.runIds.length, 30); assert.equal(run.arenaRoundId, round.id); assert.deepEqual(run.providerIds, round.providerIds); assert.throws(() => assertBenchmarkMutable(set), /LOCKED/) })
test('a new benchmark cannot be irreversibly locked below 30 unique questions', () => { const state = fixture(); const question = createQuestionBankEntry({ text: 'Read the sign', category: 'visual_text', photoId: 'photo-1', datasetId: 'dataset-1' }, state, { idFactory: () => 'short' }); const set = state.arenaBenchmarkSets[0]; set.questionIds.push(question.id); const before = JSON.stringify(state); assert.throws(() => createArenaBatch({ benchmarkSetId: set.id, providerIds: PRIMARY_ARENA_PROVIDER_IDS, locked: true }, state), /Ranking policy failed/); assert.equal(JSON.stringify(state), before) })
test('dataset lock hash is canonical and detects tampering', () => { const state = fixture(); const q1 = createQuestionBankEntry({ text: 'Question B', category: 'other', photoId: 'photo-1', datasetId: 'dataset-1', expectedAnswer: 'B' }, state, { idFactory: () => 'b' }); const q2 = createQuestionBankEntry({ text: 'Question A', category: 'other', photoId: 'photo-1', datasetId: 'dataset-1', expectedAnswer: 'A' }, state, { idFactory: () => 'a' }); const set = state.arenaBenchmarkSets[0]; set.questionIds = [q1.id,q2.id]; const first = computeBenchmarkLockHash(set, state, '1.0.0'); set.questionIds.reverse(); assert.equal(computeBenchmarkLockHash(set, state, '1.0.0'), first); q1.text = 'tampered'; assert.notEqual(computeBenchmarkLockHash(set, state, '1.0.0'), first) })
test('Blind Judge Bundle is share-safe and Private Mapping Bundle is distinct', async () => { const state = fixture(); const round = roundIn(state); round.expectedAnswer = 'secret-ground-truth'; round.expectedAnswerSource = 'USER_DEFINED_GROUND_TRUTH'; attachAnswers(state, round); revealArenaRound(round, [], { early: true }); const root = await mkdtemp(path.join(os.tmpdir(), 'arena-')); const photosDir = path.join(root, 'photos'); const inferenceDir = path.join(root, 'inference'); await mkdir(photosDir); await mkdir(inferenceDir); await writeFile(path.join(photosDir, 'dog.jpg'), 'original'); await writeFile(path.join(inferenceDir, 'dog.png'), 'inference'); const bundle = await buildArenaBundle(state, round, { photosDir, inferenceDir }); const blind = await buildArenaBundle(state, round, { photosDir, inferenceDir }, true); const privateBundle = buildPrivateMappingBundle(state, round); assert.ok(bundle.includes(Buffer.from('answers.json'))); for (const secret of [...round.providerIds, 'secret-', 'secret-ground-truth', 'USER_DEFINED_GROUND_TRUTH', 'blindMapping', 'winnerProviderId', 'latencyMs', 'runtimeVersion', 'private/blind-mapping.json']) assert.equal(blind.includes(Buffer.from(secret)), false, `blind export leaked ${secret}`); assert.ok(blind.includes(Buffer.from('BLIND_JUDGE_SHARE_SAFE'))); assert.ok(privateBundle.includes(Buffer.from('private/blind-mapping.json'))) })
test('post-reveal judgment and repeated reveal cannot alter the blind winner', () => { const state = fixture(); const round = roundIn(state); attachAnswers(state, round); for (const label of Object.keys(round.blindMapping)) recordArenaJudgment(state, { roundId: round.id, blindLabel: label, verdict: label === 'A' ? 'CORRECT' : 'WRONG' }); revealArenaRound(round, state.arenaJudgments); const winner = calculateRoundWinner(round, state.arenaJudgments).winner; assert.throws(() => recordArenaJudgment(state, { roundId: round.id, blindLabel: 'B', verdict: 'CORRECT' }), /immutable/); assert.throws(() => revealArenaRound(round, state.arenaJudgments), /already revealed/); assert.equal(calculateRoundWinner(round, state.arenaJudgments).winner, winner) })
test('Arena UI contract exposes fair workflow, audit, blind review, reveal, and exports', async () => { const html = await import('node:fs/promises').then(fs => fs.readFile(new URL('../public/index.html', import.meta.url), 'utf8')); const js = await import('node:fs/promises').then(fs => fs.readFile(new URL('../public/app.js', import.meta.url), 'utf8')); for (const text of ['Arena: confronta tre modelli','Fairness &amp; readiness audit','Reveal Models','USER_DEFINED_GROUND_TRUTH','LFM2.5-VL-450M']) assert.ok(`${html}${js}`.includes(text)); assert.ok(js.includes('Identity, runtime and latency hidden')); assert.ok(js.includes('/export/blind')); assert.ok(js.includes('/api/arena/readiness')) })

let tokenCounter = 0
function randomToken() { tokenCounter += 1; return `token${tokenCounter}` }
