import test from 'node:test'
import assert from 'node:assert/strict'
import { addQuestion, applyBlindReviewImport, applyQuestionImport, benchmarkCoverage, benchmarkDiff, blindReviewTemplate, changeDatasetMembership, cloneBenchmarkVersion, createDataset, csvTemplate, lockBenchmarkSet, lockPreview, migrateArenaBuilderState, parseDelimited, previewBlindReviewImport, previewQuestionImport, questionIssues, updateDataset, validateBenchmarkSet } from '../src/arena/builder.mjs'
import { PRIMARY_ARENA_PROVIDER_IDS, computeBenchmarkLockHash, createArenaRound, migrateArenaState } from '../src/arena/index.mjs'
import { safeZipEntryName } from '../src/export/zip.mjs'
import { readFile } from 'node:fs/promises'

function fixture() {
  const state = { schemaVersion: 4, photos: [{ id: 'p1', filename: 'one.jpg', inferenceFilename: 'one.normalized.jpg', inferenceImageSha256: 'a'.repeat(64), width: 640, height: 480, imagePipeline: { ready: true, normalized: { filename: 'one.normalized.jpg', width: 640, height: 480 } } }], datasets: [{ id: 'd1', name: 'Dataset one', photoIds: ['p1'], createdAt: '2026-01-01T00:00:00Z' }], runs: [], inferences: [], migrations: {} }
  migrateArenaState(state); migrateArenaBuilderState(state); return state
}

function populateRankingSet(state, set, prefix = 'Rank') {
  const categories = ['object_recognition','color_detail','spatial_relation','physical_context','visual_text','number_value','ui_understanding','document_understanding','chart_table','other']
  for (let index = 0; index < 30; index++) {
    const photoId = `ranking-photo-${index}`
    state.photos.push({ id: photoId, filename: `${photoId}.jpg`, inferenceFilename: `${photoId}.normalized.jpg`, inferenceImageSha256: String((index % 9) + 1).repeat(64), imagePipeline: { ready: true, normalized: { filename: `${photoId}.normalized.jpg` } } })
    state.datasets[0].photoIds.push(photoId)
    const q = addQuestion(state, { datasetId: 'd1', photoId, text: `${prefix} question ${index}?`, category: categories[index % categories.length], expectedAnswer: String(index), answerType: 'integer' })
    set.questionIds.push(q.id)
  }
}

test('builder migration is additive and idempotent', () => { const state = fixture(); const first = JSON.stringify(state); migrateArenaBuilderState(state); assert.equal(JSON.stringify(state), first); assert.equal(state.schemaVersion, 8) })
test('dataset lifecycle preserves the global photo when membership is removed', () => { const state = fixture(); const dataset = createDataset(state, { name: 'New set', description: 'Real photos' }, { now: '2026-01-02T00:00:00Z' }); updateDataset(state, dataset.id, { name: 'Renamed' }); changeDatasetMembership(state, { fromDatasetId: 'd1', toDatasetId: dataset.id, photoId: 'p1' }); assert.equal(state.photos.length, 1); assert.deepEqual(state.datasets.find(item => item.id === 'd1').photoIds, []); assert.deepEqual(dataset.photoIds, ['p1']) })
test('questions validate references and block exact duplicates while warning on near duplicates', () => { const state = fixture(); const first = addQuestion(state, { datasetId: 'd1', photoId: 'p1', text: 'What color is the dog collar?', category: 'color_detail' }); assert.ok(first.id); assert.match(questionIssues({ datasetId: 'd1', photoId: 'p1', text: 'What color is the dog collar?', category: 'color_detail' }, state).blockers[0], /Exact duplicate/); const near = questionIssues({ datasetId: 'd1', photoId: 'p1', text: 'What color is dog collar?', category: 'color_detail' }, state); assert.ok(near.warnings.some(item => item.includes('near-duplicate'))) })
test('CSV template and quoted parser preserve the documented fields', () => { assert.ok(csvTemplate().startsWith('dataset_id,image_filename,photo_id,question,category')); const rows = parseDelimited('dataset_id,image_filename,photo_id,question,category,expected_answer,expected_answer_source,notes\nd1,one.jpg,,"What is visible, exactly?",other,,,note\n'); assert.equal(rows[0].question, 'What is visible, exactly?') })
test('bulk preview resolves unique filenames and atomic invalid import does not mutate', () => { const state = fixture(); const valid = { format: 'csv', content: `${csvTemplate().split('\n')[0]}\nd1,one.jpg,,What is visible?,other,,,,,,,note\n`, benchmarkSetId: state.arenaBenchmarkSets[0].id }; const preview = previewQuestionImport(state, valid); assert.equal(preview.validRows, 1); applyQuestionImport(state, valid); assert.equal(state.questionBank.length, 1); const before = JSON.stringify(state); const invalid = { ...valid, content: `${csvTemplate().split('\n')[0]}\nd1,missing.jpg,,Broken?,other,,,,,,,\n` }; assert.throws(() => applyQuestionImport(state, invalid), /Atomic import rejected/); assert.equal(JSON.stringify(state), before) })
test('coverage and server validation require 30 unique images, objective answers and category quotas', () => { const state = fixture(); const set = state.arenaBenchmarkSets[0]; assert.equal(validateBenchmarkSet(state, set.id).valid, false); populateRankingSet(state, set); const coverage = benchmarkCoverage(state, set.id); assert.equal(coverage.total, 30); assert.equal(coverage.uniqueImages, 30); assert.equal(coverage.expectedAnswers, 30); assert.equal(validateBenchmarkSet(state, set.id).valid, true) })
test('thirty questions on one image cannot pass the adversarial ranking gate', () => { const state = fixture(); const set = state.arenaBenchmarkSets[0]; for (let index = 0; index < 30; index++) set.questionIds.push(addQuestion(state, { datasetId: 'd1', photoId: 'p1', text: `Repeated image ${index}?`, category: 'other', expectedAnswer: 'x' }).id); const validation = validateBenchmarkSet(state, set.id); assert.equal(validation.valid, false); assert.ok(validation.blockers.some(item => item.includes('unique images'))) })
test('lock preview includes roster, budget and hash; lock is immutable and clone preserves history', () => { const state = fixture(); const set = state.arenaBenchmarkSets[0]; populateRankingSet(state, set, 'Lock'); const preview = lockPreview(state, set.id, { version: '1.0.0', outputBudget: 64 }); assert.equal(preview.providerIds.length, 3); assert.equal(preview.uniqueImages, 30); assert.match(preview.lockHash, /^[a-f0-9]{64}$/); assert.throws(() => lockBenchmarkSet(state, set.id, { version: '1.0.0' }), /confirmation/); lockBenchmarkSet(state, set.id, { confirm: true, version: '1.0.0' }); const hash = computeBenchmarkLockHash(set, state, set.version); set.outputBudget = 128; assert.notEqual(computeBenchmarkLockHash(set, state, set.version), hash); set.outputBudget = 64; const clone = cloneBenchmarkVersion(state, set.id, { version: '1.1.0-draft' }); assert.equal(set.locked, true); assert.equal(clone.locked, false); assert.equal(benchmarkDiff(state, set.id, clone.id).addedQuestionIds.length, 0) })
test('blind external review exports pre-reveal, rejects leaked identity fields, imports atomically and rejects post-reveal', () => { const state = fixture(); const round = createArenaRound({ datasetId: 'd1', photoId: 'p1', question: 'What is visible?', category: 'other', providerIds: PRIMARY_ARENA_PROVIDER_IDS }, state, { random: () => .9 }); round.status = 'AWAITING_JUDGMENT'; state.arenaRounds.push(round); for (const label of Object.keys(round.blindMapping)) { const id = `i-${label}`; round.answerIds[label] = id; state.inferences.push({ id, rawOutput: `Answer ${label}` }) } const template = blindReviewTemplate(state, [round.id]); template.judgeId = 'judge-7'; for (const judgment of template.rounds[0].judgments) judgment.verdict = 'CORRECT'; assert.equal(previewBlindReviewImport(state, template).valid, true); assert.equal(applyBlindReviewImport(state, template).imported, 3); assert.ok(state.arenaReviewImports[0].payloadSha256); assert.throws(() => previewBlindReviewImport(state, { ...template, providerId: 'leak' }), /identity/); round.status = 'REVEALED'; assert.equal(previewBlindReviewImport(state, template).valid, false); assert.throws(() => applyBlindReviewImport(state, template), /already revealed/) })
test('same normalized image SHA is attached to every provider round input', () => { const state = fixture(); const round = createArenaRound({ datasetId: 'd1', photoId: 'p1', question: 'What is visible?', category: 'other', providerIds: PRIMARY_ARENA_PROVIDER_IDS }, state); assert.equal(round.inferenceImage.sha256, 'a'.repeat(64)) })
test('ZIP entry names cannot escape the archive root', () => { assert.equal(safeZipEntryName('../../secret/../photo.jpg'), 'secret/photo.jpg'); assert.equal(safeZipEntryName('images\\..\\dog?.jpg'), 'images/dog_.jpg'); assert.throws(() => safeZipEntryName('../../')) })
test('Arena UI exposes the six-step builder, bulk import and blind review workflow', async () => { const html = await readFile(new URL('../public/index.html', import.meta.url), 'utf8'); const js = await readFile(new URL('../public/app.js', import.meta.url), 'utf8'); for (const marker of ['Dataset Manager','Question Bank Builder','Guided benchmark wizard','Download CSV template','BATCH REVIEW QUEUE','Export blind review template','Preview & lock','Create primary batch']) assert.ok(`${html}${js}`.includes(marker), marker); assert.ok(js.includes('/api/arena/questions/import/preview')); assert.ok(js.includes('/api/arena/reviews/import/preview')) })
test('Quick Arena UI exposes guided sizes, advanced sampling and live progress', async () => { const html = await readFile(new URL('../public/index.html', import.meta.url), 'utf8'); const js = await readFile(new URL('../public/app.js', import.meta.url), 'utf8'); for (const marker of ['Test rapido','Rapido · 5','Medio · 10','Esteso · 20','Completo · 30','Campione bilanciato','Preferisci immagini diverse','Mescola l’ordine','PASSO 3 · AVVIA IL TEST','quick-run-status','VALUTA LE RISPOSTE','/status']) assert.ok(`${html}${js}`.includes(marker), marker) })
test('Quick Arena automatically avoids an empty starter set and explains undersized manual selections', async () => { const js = await readFile(new URL('../public/app.js', import.meta.url), 'utf8'); assert.ok(js.includes("sets.find(item => item.questionIds.length > 0)")); assert.ok(js.includes('You manually selected')) })
