import test from 'node:test'
import assert from 'node:assert/strict'
import { createRunSelection, evidenceTierForCount, migrateArenaBuilderState, resolveRunSize } from '../src/arena/builder.mjs'
import { PRIMARY_ARENA_PROVIDER_IDS, arenaDashboard, createArenaBatch, migrateArenaState } from '../src/arena/index.mjs'

function fixture(count = 40) {
  const categories = ['object_recognition','color_detail','spatial_relation','physical_context','visual_text','number_value','ui_understanding','document_understanding','chart_table','other']
  const state = { schemaVersion: 6, photos: [], datasets: [{ id: 'dataset', name: 'Dataset', photoIds: [] }], questionBank: [], arenaBenchmarkSets: [], arenaRounds: [], arenaJudgments: [], arenaBatches: [], inferences: [], runs: [], migrations: {} }
  migrateArenaState(state); migrateArenaBuilderState(state)
  const set = state.arenaBenchmarkSets[0]
  for (let index = 0; index < count; index++) {
    const photoId = `photo-${index % 20}`
    if (!state.photos.some(item => item.id === photoId)) { state.photos.push({ id: photoId, filename: `${photoId}.jpg`, inferenceFilename: `${photoId}.jpg`, inferenceImageSha256: String(index % 10).repeat(64), imagePipeline: { ready: true, normalized: { filename: `${photoId}.jpg` } } }); state.datasets[0].photoIds.push(photoId) }
    const id = `question-${index}`; set.questionIds.push(id); state.questionBank.push({ id, text: `Unique question ${index}?`, category: categories[index % categories.length], datasetId: 'dataset', photoId })
  }
  return state
}

test('run-size presets support Quick 5, Quick 10, Preview 20, Ranked 30, all and custom N', () => { assert.equal(resolveRunSize({ runSize: 'quick5' }, 40), 5); assert.equal(resolveRunSize({ runSize: 'quick10' }, 40), 10); assert.equal(resolveRunSize({ runSize: 'preview20' }, 40), 20); assert.equal(resolveRunSize({ runSize: 'ranked30' }, 40), 30); assert.equal(resolveRunSize({ runSize: 'all' }, 40), 40); assert.equal(resolveRunSize({ runSize: 'custom', customN: 17 }, 40), 17); assert.throws(() => resolveRunSize({ runSize: 'custom', customN: 41 }, 40), /exceeds/) })
test('evidence tiers preserve the 30-question primary ranking threshold', () => { assert.equal(evidenceTierForCount(5), 'QUICK_CHECK'); assert.equal(evidenceTierForCount(10), 'EXPLORATORY'); assert.equal(evidenceTierForCount(20), 'PRELIMINARY'); assert.equal(evidenceTierForCount(30), 'RANKING_ELIGIBLE') })
test('random sampling is deterministic and a different seed reshuffles membership', () => { const state = fixture(); const input = { benchmarkSetId: state.arenaBenchmarkSets[0].id, runSize: 'quick10', sampling: 'random', seed: 183729 }; const first = createRunSelection(state, input), repeated = createRunSelection(state, input), reshuffled = createRunSelection(state, { ...input, seed: 918273 }); assert.deepEqual(first.selectedQuestionIds, repeated.selectedQuestionIds); assert.notDeepEqual(first.membershipQuestionIds, reshuffled.membershipQuestionIds) })
test('shuffle changes execution order without changing sampled membership', () => { const state = fixture(); const base = createRunSelection(state, { benchmarkSetId: state.arenaBenchmarkSets[0].id, runSize: 'quick10', sampling: 'random', seed: 10 }); const shuffled = createRunSelection(state, { benchmarkSetId: state.arenaBenchmarkSets[0].id, runSize: 'quick10', sampling: 'random', seed: 10, shuffle: true, shuffleSeed: 99 }); assert.deepEqual(new Set(base.selectedQuestionIds), new Set(shuffled.selectedQuestionIds)); assert.notDeepEqual(base.selectedQuestionIds, shuffled.selectedQuestionIds); assert.equal(shuffled.seed, base.seed) })
test('balanced random distributes available categories and reports missing categories', () => { const state = fixture(); const selection = createRunSelection(state, { benchmarkSetId: state.arenaBenchmarkSets[0].id, runSize: 'quick10', sampling: 'balanced', seed: 7 }); assert.equal(Object.values(selection.categoryCounts).filter(Boolean).length, 10); assert.deepEqual(selection.missingCategories, []) })
test('balanced random prefers image diversity but never fabricates questions', () => { const state = fixture(); const selection = createRunSelection(state, { benchmarkSetId: state.arenaBenchmarkSets[0].id, runSize: 'quick10', sampling: 'balanced', seed: 77, preferImageDiversity: true }); assert.equal(selection.selectedQuestionIds.length, 10); assert.equal(selection.uniqueImageIds.length, 10); assert.ok(selection.selectedQuestionIds.every(id => state.questionBank.some(item => item.id === id))) })
test('Quick Arena batch snapshots question/image pairs, seeds, prompts, model lock and order immutably', () => { const state = fixture(); const selection = createRunSelection(state, { benchmarkSetId: state.arenaBenchmarkSets[0].id, runSize: 'quick5', sampling: 'balanced', seed: 55, shuffle: true, shuffleSeed: 66 }); const batch = createArenaBatch({ benchmarkSetId: selection.benchmarkSetId, providerIds: PRIMARY_ARENA_PROVIDER_IDS, selectionSnapshot: selection, outputBudget: 64, modelLockSnapshot: { id: 'lock', hash: 'hash' } }, state); assert.equal(batch.arenaMode, 'EXPLORATORY'); assert.equal(batch.evidenceTier, 'QUICK_CHECK'); assert.equal(batch.roundIds.length, 5); assert.equal(batch.selectionSnapshot.frozen, true); assert.equal(batch.selectionSnapshot.seed, 55); assert.equal(batch.selectionSnapshot.shuffleSeed, 66); assert.equal(batch.selectionSnapshot.prompts.length, 5); assert.equal(batch.selectionSnapshot.modelLock.id, 'lock'); assert.match(batch.selectionSnapshot.snapshotHash, /^[a-f0-9]{64}$/) })
test('exploratory KPI are calculated but excluded from primary ranking', () => { const state = fixture(); const selection = createRunSelection(state, { benchmarkSetId: state.arenaBenchmarkSets[0].id, runSize: 'quick5', sampling: 'first' }); const batch = createArenaBatch({ benchmarkSetId: selection.benchmarkSetId, providerIds: PRIMARY_ARENA_PROVIDER_IDS, selectionSnapshot: selection }, state); for (const round of state.arenaRounds.filter(item => batch.roundIds.includes(item.id))) { round.status = 'REVEALED'; round.blindStatus = 'BLIND_VALID'; for (const [label, providerId] of Object.entries(round.blindMapping)) { const id = `${round.id}-${label}`; round.answerIds[label] = id; state.inferences.push({ id, arenaRoundId: round.id, providerId, validationResult: 'VALID', latencyMs: 20 }); state.arenaJudgments.push({ roundId: round.id, blindLabel: label, verdict: label === 'A' ? 'CORRECT' : 'PARTIALLY_CORRECT', judgeProviderId: 'USER_JUDGE', judgedBeforeReveal: true }) } } const quick = arenaDashboard(state, { evidenceTier: 'QUICK_CHECK' }); const ranked = arenaDashboard(state); assert.equal(quick.metrics.length, 3); assert.equal(quick.sharedReviewedRounds, 5); assert.equal(quick.rankingEligible, false); assert.match(quick.rankingNote, /NOT INCLUDED/); assert.equal(ranked.metrics.length, 0) })
